"""empty message

Revision ID: 15ef1d83488c
Revises: 
Create Date: 2022-05-03 01:39:29.937846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ef1d83488c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'school')
    op.drop_column('User', 'firstname')
    op.drop_column('User', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('lastname', sa.VARCHAR(length=20), nullable=False))
    op.add_column('User', sa.Column('firstname', sa.VARCHAR(length=20), nullable=False))
    op.add_column('User', sa.Column('school', sa.VARCHAR(), nullable=False))
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
