"""empty message

Revision ID: e269e85e23a6
Revises: 871bef269871
Create Date: 2022-05-03 03:35:30.994041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e269e85e23a6'
down_revision = '871bef269871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('lastname', sa.String(), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'lastname')
    op.drop_column('User', 'firstname')
    # ### end Alembic commands ###
